### ISSUE TITLE
SubVerifierType installed ignored

### ISSUE THREAD

**Issue by simonmcl** [torusresearch/customauth-swift-sdk#12]
I thought setting the SubVerifierType of `.installed` meant it would check if the Twitter app was installed, or Reddit, or Facebook etc. It just seems to be ignored with no errors or warnings.

Looking through the code it looks like its only implemented inside the Google handler. Is this by design, is it only possible with google, or is this a missing feature?

If its a google-only feature, then it shouldn't be possible to assign `.installed` to the rest as its just confusing and messy

**Comment by rathishubham7** [comment]
Yes. Google OAuth allows to create web, iOS and android specific applications. Hence the .installed parameter. And it is only valid for google. 
I will add the validation for to reject in other cases. Thanks
