### ISSUE TITLE
Crash on login using Google

### ISSUE THREAD

**Issue by dbart01** [torusresearch/customauth-swift-sdk#27]
We're seeing a crash on login using Google login

This was reported on iPhone 11 Pro running iOS 15.0.2

Verifier setup for reference:
```swift
let config = SubVerifierDetails(
    loginType: .web,
    loginProvider: .google,
    clientId: "redacted",
    verifierName: "redacted",
    redirectURL: "redacted"
)

self.torus = TorusSwiftDirectSDK(
    aggregateVerifierType: .singleLogin,
    aggregateVerifierName: "redacted",
    subVerifierDetails: [config],
    network: .MAINNET
)
```

![Screen Shot 2021-11-02 at 9 24 27 AM](https://user-images.githubusercontent.com/5244861/139856013-0c4d3467-eae8-4b8e-b054-07581945d9f3.png)

**Comment by YZhenY** [comment]
can we take a look at this @michaellee8

**Comment by michaellee8** [comment]
> We're seeing a crash on login using Google login
> 
> This was reported on iPhone 11 Pro running iOS 15.0.2
> 
> Verifier setup for reference:
> 
> ```swift
> let config = SubVerifierDetails(
>     loginType: .web,
>     loginProvider: .google,
>     clientId: "redacted",
>     verifierName: "redacted",
>     redirectURL: "redacted"
> )
> 
> self.torus = TorusSwiftDirectSDK(
>     aggregateVerifierType: .singleLogin,
>     aggregateVerifierName: "redacted",
>     subVerifierDetails: [config],
>     network: .MAINNET
> )
> ```
> 
> ![Screen Shot 2021-11-02 at 9 24 27 AM](https://user-images.githubusercontent.com/5244861/139856013-0c4d3467-eae8-4b8e-b054-07581945d9f3.png)

Hello, can you provide the logs?

**Comment by dbart01** [comment]
Sorry I don't have logs. It was captured remotely by TestFlight crash reporting.

**Comment by dbart01** [comment]
I should mention that the version of TorusDirectSDK we we're using at the time was `v1.0.3`.

**Comment by michaellee8** [comment]
> Sorry I don't have logs. It was captured remotely by TestFlight crash reporting.

I see, was that reproducible? One of the possible reason causing this crash could be the use of force unwraps we previously do, which is now replaced by proper unwrap handling in latest version.

**Comment by dbart01** [comment]
It was reproducible on those devices - as in, the crash was consistent. We don't have a way to verify, right now, whether or not the new version of the SDK addresses those crashes.

**Comment by rathishubham7** [comment]
Could you send me an invitation to the app (TestFlight)?

**Comment by vantam87** [comment]
Hi @metallicalfa2, we got a crash on login using Google also. It seems the [data](https://github.com/torusresearch/customauth-swift-sdk/blob/a4fb843fabdfd19905b7e215f40ebab4a184c9ed/Sources/CustomAuth/Handlers/GoogleLoginHandler.swift#L113) is nil I think. Could you please have a look at it again?
<img width="1278" alt="Screen Shot 2022-05-06 at 09 02 04" src="https://user-images.githubusercontent.com/38578482/167054747-a2540241-97a9-4326-af86-72f610e310e7.png">

**Comment by michaellee8** [comment]
> Hi @michaellee8, we got a crash on login using Google also. It seems the [data](https://github.com/torusresearch/customauth-swift-sdk/blob/a4fb843fabdfd19905b7e215f40ebab4a184c9ed/Sources/CustomAuth/Handlers/GoogleLoginHandler.swift#L113) is nil I think. Could you please have a look at it again? We're using `CustomAuth` `2.1.0` FYI
> 
> <img alt="Screen Shot 2022-05-06 at 09 02 04" width="1278" src="https://user-images.githubusercontent.com/38578482/167054747-a2540241-97a9-4326-af86-72f610e310e7.png">

@vantam87 

Can you state the verifier configuration and version that is being used?

**Comment by vantam87** [comment]
Hi @michaellee8,

I appreciate your help in advance.

We are trying to keep `verifierId` and `idToken`, so we handle it like below. Could you please let us know if we are missing something?
```
// Custom handle signle logins to keep verifierId and idToken which was removed in the lib
private func handleSingleLogins(_ loginProvider: LoginProviders, verifier: String) -> Promise<[String: Any]> {
    let subVerifier = SubVerifierDetails(
        loginType: .web,
        loginProvider: loginProvider,
        clientId: Constants.Credential.Torus.clientId,
        verifierName: verifier,
        redirectURL: Constants.Credential.Torus.redirectURL,
        browserRedirectURL: Constants.Credential.Torus.browserRedirectURL
    )
    let customAuth = CustomAuth(
        aggregateVerifierType: .singleLogin,
        aggregateVerifierName: verifier,
        subVerifierDetails: [subVerifier],
        network: Constants.Torus.network
    )
    customAuth.authorizeURLHandler = .external
    let loginURL = subVerifier.getLoginURL()
    let (tempPromise, seal) = Promise<[String: Any]>.pending()
    customAuth.observeCallback { url in
        let responseParameters = customAuth.parseURL(url: url)
        subVerifier.getUserInfo(responseParameters: responseParameters).then { newData -> Promise<[String: Any]> in
            let verifierId = newData["verifierId"] as? String ?? ""
            let idToken = newData["tokenForKeys"] as? String ?? ""
            return customAuth.getTorusKey(
                verifier: verifier, verifierId: verifierId, idToken: idToken, userData: newData
            )
        }.done { data in
            seal.fulfill(data)
        }.catch { err in
            seal.reject(err)
        }
    }
    customAuth.openURL(url: loginURL, view: nil, modalPresentationStyle: UIModalPresentationStyle.fullScreen)
    return tempPromise
}
```

**Comment by michaellee8** [comment]
@vantam87 by any chance u can have a log to the actual request used in the login process? Like some sort of request logger with charles proxy or proxyman?

**Comment by vantam87** [comment]
Hi @michaellee8,

Thank you for your quick response.

We cannot reproduce the crash from our side, we got it from firebase crashlytics. It rarely happens in our application. The crash report that the data (in this line https://github.com/torusresearch/customauth-swift-sdk/blob/a4fb843fabdfd19905b7e215f40ebab4a184c9ed/Sources/CustomAuth/Handlers/GoogleLoginHandler.swift#L113) is null, is it possible to omit force unwrap it?

**Comment by michaellee8** [comment]
Sure, let me make a patch that can prevent the force unwrap. @vantam87

**Comment by vantam87** [comment]
cool, thanks @michaellee8
