### ISSUE TITLE
Xcode 12.1 compile issues with cocoapods

### ISSUE THREAD

**Issue by xhzth70911** [torusresearch/customauth-swift-sdk#33]
Xcode 12.1,I'm trying to integrate this pod into an app using cocoapods,Torus-fetchNodeDetails and CryptoSwift  report errors，
![image](https://user-images.githubusercontent.com/24982706/153356779-866abc1c-86e8-4ccc-a532-ac4b376e1958.png)

cocopods pod 'CustomAuth', '~> 2.0.0'，Dependency Library
![image](https://user-images.githubusercontent.com/24982706/153358427-07afcfcd-8728-4c12-a2d0-6e6f9daad740.png)

**Comment by metallicalfa** [comment]
@michaellee8  Please take a look at this
