### ISSUE TITLE
Crash on login using Google

### ISSUE THREAD

**Issue by vantam87** [torusresearch/customauth-swift-sdk#47]
Hi @michaellee8 ,

Thank you for your help on the [issue](https://github.com/torusresearch/customauth-swift-sdk/issues/27) again.

Could you please check the function [getVerifierFromUserInfo](https://github.com/torusresearch/customauth-swift-sdk/blob/93212bcbbe181d19978ee54fb317fa45a5f4e292/Sources/CustomAuth/Handlers/GoogleLoginHandler.swift#L65)?
We still get crashes from GoogleloginHandler in the latest version 4.1.0. Is it possible to omit force unwrap it also?
```Swift
func getVerifierFromUserInfo() -> String {
        return self.userInfo!["email"] as! String
}
```

Thank you in advance

**Comment by michaellee8** [comment]
@vantam87 I no longer work for Web3Auth, @dhruvTor can you take over this? I think it should be ok to make it return empty string if the field is not populated and then cause it to fail gracefully.

**Comment by dhruvTor** [comment]
Yes let me have a look into this

**Comment by dhruvTor** [comment]
Hey @vantam87 the new version of CustomAuth swift sdk (4.1.1) has been released with the fix, If you are using cocoapods please try after an hour or so cause it's CI takes some time, Do let me know if you face any issue.

**Comment by vantam87** [comment]
@dhruvTor thank you for your quick response. 🙏

**Comment by vantam87** [comment]
This was fixed in [PR](https://github.com/torusresearch/customauth-swift-sdk/pull/48)
