### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by simonmcl** [torusresearch/customauth-swift-sdk#56]
you added macos support 10.15 to all the other swift packages (torus utils, fetch node details etc). But left this one blank. When you leave it blank, it defaults to 10.13 under the hood. This conflicts with the other packages set to 10.15, causing it to throw an error. This doesn't just affect MacOS support, but also causes issues inside Xcode 14.3 for iOS now that they've dropped rosetta as the default option. 

Can you either try drop torus utils + fnd to 10.13 or add 10.15 to this one please

**Comment by simonmcl** [comment]
cc: @chaitanyapotti

**Comment by simonmcl** [comment]
@chaitanyapotti ... doesn't compile

![Screenshot 2023-07-17 at 15 25 22](https://github.com/torusresearch/customauth-swift-sdk/assets/8058386/58113ada-1ddd-4aea-b2b4-c9cc1ddbef23)

**Comment by chaitanyapotti** [comment]
It actually doesn't compile for macOS. That's why it didn't include it before. I added the macOS setting to fix your issue. You shouldn't actually compile it for macOS.

**Comment by chaitanyapotti** [comment]
Alternatively, I can drop macOS support everywhere. This and other torus packages are intended for iOS only.

**Comment by simonmcl** [comment]
@chaitanyapotti I requested MacOS in the past, because we have plans to build desktop app eventually. I wasn't requesting that a setting be turned on for no reason. Is MacOS support something you can add to your roadmap? I would assume the only thing that needs to change is how the browser is opened, which shouldn't be a huge lift

**Comment by simonmcl** [comment]
@chaitanyapotti hi this is still causing me issues with tooling. If macos is not supported, can you please remove it?
