### ISSUE TITLE
Xcode 12.5 compile issues with cocoapods

### ISSUE THREAD

**Issue by simonmcl** [torusresearch/customauth-swift-sdk#7]
Hi,

I'm trying to integrate this pod into an app using cocoapods and i'm getting complication errors from an outdated version of CryptoSwift. And a warning that there is "No rule to process" one of the bundled json files for arm64 arch.

![Screenshot 2021-06-17 at 16 39 29](https://user-images.githubusercontent.com/8058386/122429695-e1766000-cf8a-11eb-8ca5-b887391fa6bb.png)

CryptoSwift is aware of the build errors issue and fixed it, seems you are using one that is out of date: https://github.com/krzyzanowskim/CryptoSwift/issues/870

**Comment by SaleemFlatCircle** [comment]
Having this issue as well

**Comment by SaleemFlatCircle** [comment]
Seems to be because the Torus-utils dependency is dependent on Torus-fetchNodeDetails which is dependent on web3swift which is dependant on CryptoSwift version 1.0.0, an older version of CryptoSwift thats causing these errors in Xcode 12.5+

**Comment by phuctm97** [comment]
Hi @SaleemFlatCircle, one workaround now is to go to your Flutter project `/ios/Podfile`, add this line

```ruby
target 'Runner' do
  use_frameworks!
  use_modular_headers!
 
  # Add this line
  pod 'web3swift', :git => 'https://github.com/lvyikai/web3swift.git', :branch => 'develop'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

Let me know if it works for you.

**Comment by SaleemFlatCircle** [comment]
I can confirm the above workaround does work

**Comment by phuctm97** [comment]
Thanks @SaleemFlatCircle, if it is resolved, please close the issue 🙏🏻

**Comment by simonmcl** [comment]
@phuctm97 he has only proposed a workaround, it doesn’t fix the issue for everyone else. Also I was the one that opened the issue.

The dependencies of this library need to be updated to fix the issue permanently
